### ISSUE TITLE
офф сток

### ISSUE THREAD

**Issue by framki** [sc16me/santa-atmo#1]
`hekate_ipl.ini`
```sh
# Both above disable kernel patching
# Stock All FW, includes exosphere and warmboot, ONLY when >= 7.0.0.
stock=1
emummc_force_disable=1
```
как повод добавить `stock=1` для тех кто хочет иметь возможность зайти на полностью чистый сток для онлайна

**Comment by sc16me** [comment]
Да, но с параметром stock=1 атма не грузилась, по крайней мере на 0.12.x Посмотрю, может исправили, или секрет какой есть... На 0.11.x ключ работал.

**Comment by sc16me** [comment]
Добавил, работает.
