### ISSUE TITLE
Вопрос: обновление сборки через DBI

### ISSUE THREAD

**Issue by Rineko** [sc16me/santa-atmo#2]
Есть ли возможность обновить сборку, перезаписав необходимые файлы через DBI (включая DBI), и перезагрузившись после этого (чтобы не вытаскивать лишний раз SD-карту)?
(например, с atmo-0.19.0-130421 на atmo-0.19.2-040521)

**Comment by sc16me** [comment]
Сама атмосфера не даст перезаписать свои файлы на горячую. Раньше такая возможность была, но теперь нет. Как вариант, перезагрузится в Hekate и смонтировать sdcard к компу по проводу.
