### ISSUE TITLE
Поддержка USB3.0 в DBI.

### ISSUE THREAD

**Issue by Rineko** [sc16me/santa-atmo#3]
Просьба, если есть возможность, в следующем релизе дописать в system_settings.ini в атме строчку для включения поддержки usb3.0 для dbi:
`usb30_force_enabled = u8!0x1`

**Comment by sc16me** [comment]
Ранее с этим были проблемы. Какие именно уже не помню, но народ жаловался на работу usb 2.0 при включенном usb 3.0. Попробую протестировать, если проблем не возникнет, добавлю.
